"""JavaScript-semantics helpers.

The finance conformance vectors were generated by a TypeScript reference, so
every place the reference leans on a JavaScript primitive — ``Math.round``,
``Number.prototype.toFixed``, ``String(x)``, ``typeof x === "number"``,
``.length`` on a string, the default ``Array.prototype.sort`` — has to be
reproduced here exactly, not "improved". These helpers isolate that surface
so the ported modules read like the reference and the quirks are named.
"""

from __future__ import annotations

import math
from decimal import ROUND_HALF_UP, Decimal
from typing import Any

from ..core.canonical import _js_number


def is_js_number(x: Any) -> bool:
    """``typeof x === "number"``: ints and floats, but not bools (a bool is
    an int subclass in Python and a distinct type in JavaScript)."""
    return isinstance(x, (int, float)) and not isinstance(x, bool)


def is_finite_number(x: Any) -> bool:
    """``typeof x === "number" && Number.isFinite(x)``."""
    if not is_js_number(x):
        return False
    return math.isfinite(x) if isinstance(x, float) else True


def js_round(x: float) -> float:
    """``Math.round``: nearest integer, ties toward +infinity. Python's
    ``round`` is banker's rounding and ``floor(x + 0.5)`` mis-rounds
    0.49999999999999994, so this is done the way the spec describes it."""
    if not math.isfinite(x):
        return x
    r = math.floor(x)
    if x - r >= 0.5:
        r += 1
    return float(r) if not isinstance(x, int) else r


def js_string_length(s: str) -> int:
    """``s.length`` counts UTF-16 code units, not code points."""
    return len(s.encode("utf-16-le")) // 2


def js_string(x: Any) -> str:
    """``String(x)`` for JSON-shaped values."""
    if x is None:
        return "null"
    if x is True:
        return "true"
    if x is False:
        return "false"
    if isinstance(x, str):
        return x
    if isinstance(x, (int, float)):
        if isinstance(x, float) and math.isnan(x):
            return "NaN"
        if isinstance(x, float) and math.isinf(x):
            return "Infinity" if x > 0 else "-Infinity"
        return _js_number(x)
    if isinstance(x, (list, tuple)):
        return ",".join("" if e is None else js_string(e) for e in x)
    if isinstance(x, dict):
        return "[object Object]"
    return str(x)


def js_sort_key(s: str) -> bytes:
    """Default ``Array.prototype.sort`` compares strings by UTF-16 code
    unit; Python compares by code point. They differ only above the BMP,
    but a hash is a hash."""
    return s.encode("utf-16-be")


def js_number_of(s: str) -> float:
    """``Number(s)`` for the digit strings ``dayNumber`` sees. Empty or
    whitespace-only is 0; anything unparsable is NaN."""
    t = s.strip()
    if t == "":
        return 0.0
    try:
        return float(t)
    except ValueError:
        return math.nan


def js_to_fixed(x: float, digits: int) -> str:
    """``Number.prototype.toFixed(digits)`` for |x| < 1e21: round the exact
    decimal expansion of the double half-up (ties pick the larger n, i.e.
    away from zero on the magnitude), and never print a negative zero."""
    if not math.isfinite(x):
        return js_string(x)
    if abs(x) >= 1e21:
        return js_string(x)
    if x == 0:
        x = 0.0  # (-0).toFixed(2) is "0.00"; (-0.001).toFixed(2) is "-0.00" and stays so
    q = Decimal(1).scaleb(-digits)
    return format(Decimal(x).quantize(q, rounding=ROUND_HALF_UP), "f")
